### ISSUE TITLE
Footer copyright text problem 

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#100]
User @mojdeeeeeh 

Footer COPYRIGHT text must be realigned, it exceeds from the bottom of page.

Check in low resolution screens

Thanks

**Comment by mojdeeeeeh** [comment]
I Add more height for that

**Comment by Ojvar** [comment]
User @mojdeeeeeh 

And what's the result?

Is it ok, or not?
If OK then please close the issue

thanks
