### ISSUE TITLE
Error in watch list

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#101]
Users @Mahdi-Dzh , @mojdeeeeeh 

In page:
http://amax.io/pages/amax_ai/algorithm_result

When user mark a symbol as Favourite in watch-list nevertheless server sends:
{"status":200,"data":"watch_list.remove.send_successfully"},

But user view the error message
And No Symbol has been saved as Favourite iin WatchList page

Fix this bug as soon

Thanks

**Comment by mojdeeeeeh** [comment]
Fix this..

**Comment by Ojvar** [comment]
User @mojdeeeeeh 

Please fix the save problem

**Comment by mojdeeeeeh** [comment]
در لوکال سیو میشه و نمایش اطلاعات دارم

**Comment by Mahdi-Dzh** [comment]
@Ojvar 
It was fixed.
