### ISSUE TITLE
Validation bug

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#102]
User @mojdeeeeeh 

In page:
http://amax.io/pages/user/create

User validation is invalid, 
**Dont' Show any message below Phone number textbox!!!**

**Comment by mojdeeeeeh** [comment]
متوجه نشدم!
اما برای شماره تلفن  با توجه به خطا کاربری برای ثبت شماره، زیر باکس پیام مشاهده میشه

**Comment by mojdeeeeeh** [comment]
Done
