### ISSUE TITLE
Missing username 

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#103]
User @mojdeeeeeh 

In page:
http://amax.io/pages/amax_ai/algorithm_result

Username should be displayed in Title as other pages

**Comment by mojdeeeeeh** [comment]
برای هدر یا عنوان صفحات؟
برای هدر که ابتدا هیچ متنی نمیخواستن نمایش بدن 
بعدا گفتن اعتبار نمایش بدیم اما اسم کاربر نه
برای عنوان ها هم همه رو طبق درخواست خودشون زدم 
فقط صفحه اول انیمشن باشه سایر صفحات عنوان نداشته باشه

**Comment by Ojvar** [comment]
Ok
