### ISSUE TITLE
MarketPower Error

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#105]
User @Mahdi-Dzh 

**Undefined index: market_power {"exception":"[object] (ErrorException(code: 0): Undefined index: market_power at  /app/MarketPower.php:41)**

**Comment by Ojvar** [comment]
Fixed

User @Mahdi-Dzh 
Please verify the changes

**Comment by Mahdi-Dzh** [comment]
@Ojvar 
Please run AlgorithmTableSeeder to fix this problem.
Thanks

**Comment by Ojvar** [comment]
It was run!
