### ISSUE TITLE
scroll

### ISSUE THREAD

**Issue by mojdeeeeeh** [Ojvar/ExchangePrediction#119]
http://www.amax.io/pages/amax_ai/algorithm_result
برای صفحه هوش مصنوعی نتایج الگوریتم ها دارای اسکرول است که باید در بالا یا پایین صفحه دکمه نمایش یا مخفی شوند
همچنین برای ۱. کارد نتایج الگوریتم ۲. انتخاب الگوریتم و صفحه نتایج کمپانی ۳. تعداد الگوریتم پیشنهادی و ایجاد تحلیل برای لیست قوانین سایت، /علامت چشمک زن/ وجود دارد. که میخواد علامت در انتهای لیست که رسید حذف بشه

**Comment by Ojvar** [comment]
User @mojdeeeeeh 

Please resolve this issue!

**Comment by mojdeeeeeh** [comment]
سلام
این متن در قالب کامنت نزدم
علامت چشمک زن رو من قبل عید به شما نشون دادم
که نتونستم با اسکرول در یک المنت خاص اونو مخفی کنم یا رسید به انتهای لیست
حذف بشه
که شما گفتید یکیشو حلش میکنید در ایشوو ها قرار بدم

**Comment by Ojvar** [comment]
User @mojdeeeeeh 

One sample is implemented in page:
Algorithm results

**Comment by mojdeeeeeh** [comment]
نمونه اجرا شده در پروژه برای علامت چشمک زن پیدا نکردم

**Comment by mojdeeeeeh** [comment]
_نمونه اجرا شده در پروژه برای علامت چشمک زن پیدا نکردم_

راه حلی پیدا کردم یک عنصر داخل 
div با اسکرول مخفی بشه
اما این راه فقط با اسکرول مخفی میشه 
با کل عنصر کار نداره که لیست چقدر طولانی باشه
نمونه کد برای resources/views/amax_ai/index.blade.php
در برنچ showHide

**Comment by Ojvar** [comment]
Done!

**Comment by mojdeeeeeh** [comment]
i do this for other pages

**Comment by mojdeeeeeh** [comment]
The resource from “http://localhost:5000/tem/contactform/contactform.js”
was blocked due to MIME type (“text/html”) mismatch
(X-Content-Type-Options: nosniff).[Learn More]

**Comment by mojdeeeeeh** [comment]
[Vue warn]: Error in render: "TypeError: can't assign to property "extra"
on "<!DOCTYPE html>\n<html>\n    <head>\n        <title>\n
 Exchange\n        </title>\n\n        <link rel=\"icon\" href=\"
http://localhost:8000/images/image.png\" sizes=\"any\"
type=\"image/png\">\n\n        <meta charset=\"UTF-8\" />\n\n        <meta
name=\"csrf-token\"\n
 content=\"4XYsH3Rk64rhdpRmTVNzXxnTOSTA5zF26UmreNo4\" />\n\n        <meta
name=\"viewport\"\n              content=\"width=device-width,
initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />\n\n\t    <meta
name=\"theme-color\"\n              content=\"#071b28\" />\n\n        <link
rel=\"stylesheet\"\n              href=\"
http://localhost:8000/template/css/main.css\" />\n\n        <link
rel=\"stylesheet\"\n              href=\"
http://localhost:8000/template/css/linearicons.css\" />\n\n        <link
rel=\"stylesheet\"\n              href=\"
http://localhost:8000/template/css/font-awesome.min.css\" />\n\n
 <link …
app.js:37812:7

**Comment by mojdeeeeeh** [comment]
اخرین تغییرات
