### ISSUE TITLE
Reformat and Redesign /Pages/Trade result tables

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#122]
User @mojdeeeeeh 

In page:
/Pages/Trade

Please Review and Redesign results table

**Comment by mojdeeeeeh** [comment]
i have error in this page 
Undefined property: stdClass::$company

**Comment by Ojvar** [comment]
Please copy and paste error logs here

**Comment by mojdeeeeeh** [comment]
_Error in network:_
**Header:** 
 http://localhost:8000/pages/trade/data/get_trades?page=1
-----------------
**Response:** 
message | Undefined property: stdClass::$company
exception | ErrorException
file | /home/mojdeh/Documents/WebSite/ExchangePrediction/vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php
line | 116

**Comment by Ojvar** [comment]
Please look at the 
http://amax.io/pages/trade/data/last_update

There is no problem
Check your local repository

**Comment by mojdeeeeeh** [comment]
Done
