### ISSUE TITLE
user promote

### ISSUE THREAD

**Issue by mojdeeeeeh** [Ojvar/ExchangePrediction#13]
سطح کاربری در صفحه ارتقا کاربر نمایش داده شود

**Comment by mojdeeeeeh** [comment]
سطح کاربری با توجه به تغییر انجام شده در ظاهر صفحه قرار داده شود

**Comment by Mahdi-Dzh** [comment]
@lang('user_upgrade.first_text', ['promote' => \Auth::user()->activePromote()->title])
