### ISSUE TITLE
اصلاح نحوه نمایش گزارش نتایج الگوریتمها

### ISSUE THREAD

**Issue by Mahdi-Dzh** [Ojvar/ExchangePrediction#136]
نحوه نمایش گزارش نتایج الگوریتمها اصلاح شود. به شکل بهتری نمایش داده شود شبیه به صفحه نمایش نتایج الگوریتمها برای کاربران
قبل از انجام با آقای محمدپور هماهنگ شوید

**Comment by mojdeeeeeh** [comment]
Done
