### ISSUE TITLE
مشکل انتخاب اهرم تحلیل

### ISSUE THREAD

**Issue by Mahdi-Dzh** [Ojvar/ExchangePrediction#137]
هنگام انتخاب اهرم تحلیل در بخش ثبت تحلیل در گوشی آیفون مشکل وجود دارد. در این بخش اهرم تحلیل قابل انتخاب نیست

**Comment by Ojvar** [comment]
User @mojdeeeeeh 
Please convert all Select tags with Bootstrap dropdown
