### ISSUE TITLE
Market Seniment

### ISSUE THREAD

**Issue by Mahdi-Dzh** [Ojvar/ExchangePrediction#138]
@mojdeeeeeh 
This route:
Route::get ('/pages/amax_ai/market_sentiment', 'MarketPowerController@loadTodaySentiment')
         ->name ('amax_ai.load_market_sentiment');

**on the sentiment branch**

Like market power by all descriptions that i sent to your whatsapp.

**Comment by mojdeeeeeh** [comment]
Done
check it!
