### ISSUE TITLE
Company Seniment in info page

### ISSUE THREAD

**Issue by Mahdi-Dzh** [Ojvar/ExchangePrediction#139]
@mojdeeeeeh 
Add new feature to info page by this route:
Route::get ('/pages/amax_ai/company_sentiment/{company_id}',
            'MarketPowerController@companySeniment')
     ->name ('amax_ai.company_sentiment');

**on the sentiment branch**

I sent to your whatsapp description.

**Comment by mojdeeeeeh** [comment]
Done
but we have big number like:
0.67289719626168
45880.1
its true?

**Comment by Ojvar** [comment]
User @Mahdi-Dzh 

Please resolve this problem
Thanks
