### ISSUE TITLE
Problem in Suggested Algorithm list in Algorithm result

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#146]
I select PreTex1 + PreTex2 + PreTex3 + BPA and BPA+

and in the intersection list (final list) I Select
 داروسازی زاگرس فارمد پارس (ددام) 
to show statistics 

but in the Statistics result, 
I see that :

 الگوریتمی این نماد را پیشنهاد نداده است 

Is it correct while I select the Symbol form outptu list (intersection list) ?

Please check the UI and BackEnd for the problem
Thanks

**Comment by Mahdi-Dzh** [comment]
بررسی شد و تکرار این مساله مشاهده نگردید
