### ISSUE TITLE
مشکل نمایش نماد در صفحه هوش مصنوعی

### ISSUE THREAD

**Issue by Mahdi-Dzh** [Ojvar/ExchangePrediction#147]
@mojdeeeeeh 
در قسمت
pages/amax_ai/algorithm_result
بخش انتخاب نماد، وقتی نماد (زدشت) انتخاب میشود، به دلیل بزرگ بودن نام نماد، قسمتی از آن بیرون قرار میگیرد
لطفا بررسی کنید

**Comment by mojdeeeeeh** [comment]
@Ojvar 
ADD CSS for company-list component
 white-space: normal 
 word-wrap break-word

**Comment by Ojvar** [comment]
Fixed.
Add css to compnay-list.vue
