### ISSUE TITLE
pages/user-management,   Error 402

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#3]
I receive an Error 402
When I try to send a message to a user 
with
 subject "Hello" 
  text      " Hi roooooooooooooooooooooot"

Solution: Check subject length in VeeValidate

**Comment by mojdeeeeeh** [comment]
Hi.
The Hello is 5 characters but it must be 6 characters.
vee-validate accept *space in end, but MessageRequest not accept that.
