### ISSUE TITLE
مشکل نمایش نمودار وضعیت کاربر

### ISSUE THREAD

**Issue by Mahdi-Dzh** [Ojvar/ExchangePrediction#49]
مشکل css
 نمودار نمایش آماری وضعیت کاربر
نمایش pie chart
مشکل دارد
برای نمایش باید f12 زده شود

**Comment by Ojvar** [comment]
Please explain the problem in human readable and well-formatted text.
thnx

**Comment by mojdeeeeeh** [comment]
مودال برداشته شد 
نمودار درست نمایش میدهد
