### ISSUE TITLE
Page design: pages/amax_ai/algorithm_result

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#53]
در صفحه 
pages/amax_ai/algorithm_result

ترکیب صفحه به صورت زیر پیاده سازی شود

**[ انتخاب نماد ]**
### **یا**
**[انتخاب الگوریتم]**

* کلمه "یا" از جمله انتخاب الگوریتم حذف شود

**Comment by mojdeeeeeh** [comment]
Done
