### ISSUE TITLE
about amax

### ISSUE THREAD

**Issue by mojdeeeeeh** [Ojvar/ExchangePrediction#58]
تغییر فضای ظاهری دربارهamax

**Comment by mojdeeeeeh** [comment]
قرار دادن دکمه برای نمایش و مخفی کردن اطلاعات انجام شد.
متن درباره امکس باید کامل شود و قرار داده شود

**Comment by Ojvar** [comment]
User @mojdeeeeeh 

Please set state of this issue.
Should it closed or not?

**Comment by mojdeeeeeh** [comment]
Done
