### ISSUE TITLE
History Algorithm

### ISSUE THREAD

**Issue by mojdeeeeeh** [Ojvar/ExchangePrediction#61]
کاربر بتواند تاریخچه الگوریتم های انتخابی اش را ببیند
این صفحه به گونه ای باشد که مدیر تاریخچه تمام کاربران و هر کاربر تاریخچه خود را ببیند

**Comment by Mahdi-Dzh** [comment]
@mojdeeeeeh 
Backend completed. Just needs to frontend.
Thanks.

**Comment by mojdeeeeeh** [comment]
Done
