### ISSUE TITLE
spGetTrades Procedure Bug

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#69]
User @Mahdi-Dzh 

Please pull new source and RECHECK **spGetTrades** procedure codes.
Thanks

**Comment by Mahdi-Dzh** [comment]
I tried to update but my result was "Already up to date."

**Comment by Ojvar** [comment]
Ok
I updated it,
Please try again, and have look again.

Thanks

**Comment by Ojvar** [comment]
Ok
I updated it,
Please try again, and have look again.

Thanks

**Comment by Mahdi-Dzh** [comment]
@Ojvar 
نگاه کردم
**spGetTrades**
هیچ تغییری نکرده

**Comment by Ojvar** [comment]
It has chages!
Look more closely
