### ISSUE TITLE
clock

### ISSUE THREAD

**Issue by mojdeeeeeh** [Ojvar/ExchangePrediction#7]
در سایت نمایش زمان داشته باشیم.

**Comment by Mahdi-Dzh** [comment]
انجام شد و در
header.blade.php
قرار گرفت
نیاز به تغییرات
css
دارد

**Comment by mojdeeeeeh** [comment]
style clock need to change
http://localhost:8000/pages/guess/data/view

**Comment by mojdeeeeeh** [comment]
ساعت باید از سرور خوانده شود نه از کلاینت.

**Comment by Ojvar** [comment]
Recently Vue-Clock component has been removed
New Custome Vue-Clock component was added
