### ISSUE TITLE
Error in View algorithm result page

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#76]
User @mojdeeeeeh 

I had select multiple of algorithm 
and then click on view button

But...
I viewed this 

     الگوریتمی انتخاب نشده است 

4 Whats?

**Comment by mojdeeeeeh** [comment]
زمانی که الگوریتم دیتا نداشته باشه این رخ میده. که درنظر داشتم صحبت کنیم این الگوریتم ها انتخاب نشن.

**Comment by Mahdi-Dzh** [comment]
@Ojvar 
It was fixed.
