### ISSUE TITLE
Algorithm_result page

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#81]
User @mojdeeeeeh 
In page:
http://amax.io/pages/amax_ai/algorithm_result

When I choose a symbol, I only can select OK button,
Users should be able to choose **YES/NO** options

You can add a new **NO** button to cancel operation

Thanks

**Comment by mojdeeeeeh** [comment]
دکمه  انصراف وجود داشت..
 اما مشتری شدیدا خواهان حذف این دکمه ها در مودال هست 
به نظر ایشون دکمه بستن در بالای مودال کافیه
