### ISSUE TITLE
Move serach icon to center

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#82]
User @mojdeeeeeh 

In page:
http://localhost:8000/pages/amax_ai/algorithm_result

In second button (Select Algorithm)
Please move {magnify icon} to center 

Thanks

**Comment by mojdeeeeeh** [comment]
اینکه ایکون دکمه کنار باشه انتخاب مشتری بود
بعد از قرار دادن تایید کرده.
مشابه ایکون سرچ گوگل مد نظر داشت

**Comment by mojdeeeeeh** [comment]
اندک فاصله ایکون لحاظ شد
