### ISSUE TITLE
Add "Rials" word

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#83]
User @mojdeeeeeh 

In page:
http://localhost:8000/payment/zarinpal/request

Please add a "Rials" next to "Price" comboBox

Thanks

**Comment by mojdeeeeeh** [comment]
کنار باکس قیمت قرار بدم باید اندازه باکس نسبت به بقیه کوچک  تر بشه
مخصوصا در موبایل ویو 
لطفا نگاه کنید اگه خوبه این روش

**Comment by mojdeeeeeh** [comment]
مشکل ظاهری لیبل کنار سلکت باکس برطرف شد و ریال شامل باکس قرار گرفت
