### ISSUE TITLE
Unreadable date values on chart legend

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#88]
User  @mojdeeeeeh 

In page:
http://amax.io/pages/user_statistic

User can't read DATE VALUES of chart's legend
It must rotated at 90 degrees.

Thanks

**Comment by mojdeeeeeh** [comment]
سلام من دیتا درست درلوکال ندارم ندیده بودم
اما با توجه به تغییرات سی اس اس انجام شد
باز باید در سرور بررسی بشه

**Comment by Ojvar** [comment]
What output was make?

**Comment by Ojvar** [comment]
User @mojdeeeeeh 

Please check the problem and try to solve if it was not fixed!

Thansk

**Comment by mojdeeeeeh** [comment]
Make data and solve it.
