### ISSUE TITLE
Select  symbol

### ISSUE THREAD

**Issue by mojdeeeeeh** [Ojvar/ExchangePrediction#9]
تغییرات ظاهری و متنی دارد

**Comment by mojdeeeeeh** [comment]
جستجو در نماد:
۱- جستجو در *نام + نماد* انجام شود
۲- دسته بندی بر حسب نماد
۳- دسته بندی *همه* لیست
دکمه انتخاب در مودال حذف شود
رنگ حذف شود alternating

**Comment by Ojvar** [comment]
Done !
