### ISSUE TITLE
Load Python Modules Dynamically

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#90]
User @Mahdi-Dzh 

To learn about **How to Dynamicllay load modules in Python**
Checkout branch: **pythonDynamicModule**

Note:
##
##

**Comment by Mahdi-Dzh** [comment]
@Ojvar 
صبح این کار رو به شکل دیگه انجام دادم

**Comment by Ojvar** [comment]
Compare with suggested method and use the advantages of that
The suggested method load all python classess dynamically and Don't need to dbase for load and recognize clasess
