### ISSUE TITLE
تومان

### ISSUE THREAD

**Issue by mojdeeeeeh** [Ojvar/ExchangePrediction#93]
تبادلات مالی به تومان تغییر کند

**Comment by mojdeeeeeh** [comment]
در صفحات کاربری از نظر ظاهری ریال به تومان تغییر کرد
 اما صفحات تراکنش مالی اعتباری باید بررسی بشه
و در کنترلر زرین پال نیز مبلغ ورودی کاربر در ۱۰ ضرب بشه بعد به زرین پال ارسال بشه

**Comment by Ojvar** [comment]
Use @Mahdi-Dzh 

Please check the pages using zarinPal & credits
