### ISSUE TITLE
Some changed on migrations

### ISSUE THREAD

**Issue by Mahdi-Dzh** [Ojvar/ExchangePrediction#96]
@Ojvar 
Please migrate again the following migrations on server
**2019_02_26_114623_create_amax_procedures_3
2019_02_28_174445_create_correlation_companies_table**
and run **algorithms table seeder** to update algorithms.

**Comment by Ojvar** [comment]
User @Mahdi-Dzh 

2019_02_28_174445_create_correlation_companies_table

Not found!

**Comment by Mahdi-Dzh** [comment]
@Ojvar 
There are all migrations in last update.
