### ISSUE TITLE
UI Problem

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#99]
User @mojdeeeeeh 

In page:
http://amax.io/pages/amax_ai/algorithm_result

When user select 1 or more algorithm(s) then click on view button,
if no data exists for all of them, user just view this error:
 الگوریتمی انتخاب نشده است

But, you must show the selected algorithms and then show this message

thanks

**Comment by Mahdi-Dzh** [comment]
@Ojvar 
It was fixed.
